sonar.projectKey=mr-jenk
sonar.projectName=Buy01 E-commerce Microservices
sonar.projectVersion=1.0

sonar.sourceEncoding=UTF-8

sonar.sources=\
backend/discovery-service/src/main,\
backend/gateway-service/src/main,\
backend/user-service/src/main,\
backend/product-service/src/main,\
backend/media-service/src/main,\
backend/order-service/src/main,\
frontend/src

sonar.tests=\
backend/gateway-service/src/test,\
backend/user-service/src/test,\
backend/product-service/src/test,\
backend/media-service/src/test,\
backend/order-service/src/test,\
frontend/src

sonar.exclusions=\
**/target/**,\
**/node_modules/**,\
**/dist/**,\
**/coverage/**,\
frontend/src/**/*.spec.ts

sonar.test.inclusions=\
backend/**/src/test/**/*.java,\
frontend/src/**/*.spec.ts

sonar.java.binaries=\
backend/discovery-service/target/classes,\
backend/gateway-service/target/classes,\
backend/user-service/target/classes,\
backend/product-service/target/classes,\
backend/media-service/target/classes,\
backend/order-service/target/classes

sonar.java.test.binaries=\
backend/gateway-service/target/test-classes,\
backend/user-service/target/test-classes,\
backend/product-service/target/test-classes,\
backend/media-service/target/test-classes,\
backend/order-service/target/test-classes

sonar.coverage.jacoco.xmlReportPaths=\
backend/gateway-service/target/site/jacoco/jacoco.xml,\
backend/user-service/target/site/jacoco/jacoco.xml,\
backend/product-service/target/site/jacoco/jacoco.xml,\
backend/media-service/target/site/jacoco/jacoco.xml,\
backend/order-service/target/site/jacoco/jacoco.xml

sonar.javascript.lcov.reportPaths=frontend/coverage/frontend/lcov.info

sonar.junit.reportPaths=\
backend/gateway-service/target/surefire-reports,\
backend/user-service/target/surefire-reports,\
backend/product-service/target/surefire-reports,\
backend/media-service/target/surefire-reports,\
backend/order-service/target/surefire-reports

sonar.coverage.exclusions=\
backend/discovery-service/**,\
**/*Application.java,\
**/config/**,\
**/dto/**,\
**/model/**,\
frontend/src/main.ts,\
frontend/src/**/*.spec.ts
